[package]
name = "ovo-qjs"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
url    = { workspace = true }

[build-dependencies]
bindgen = "0.70.1"
cc = "1.1.30"
