[package]
name = "ovo"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ovo-qjs = { workspace = true }

clap = { workspace = true, features = ["derive"] }
